import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { readFile } from "node:fs/promises";

const here = dirname(fileURLToPath(import.meta.url));

/** The Foundry repo root, one level above `web/`. */
export const REPO_ROOT = resolve(here, "..", "..");
export const OUT_DIR = resolve(REPO_ROOT, "out");
export const DEPLOYMENTS_DIR = resolve(REPO_ROOT, "deployments");
export const BROADCAST_DIR = resolve(REPO_ROOT, "broadcast");
export const GENERATED_DIR = resolve(here, "..", "src", "generated");

/**
 * Contracts the app binds to.
 *
 * Deliberately an allowlist rather than a glob over `out/`: that directory also
 * contains every dependency, every test and every script artifact, and generating
 * bindings for all of them would bury the fifteen that matter.
 */
export const CONTRACTS = [
  "Marketplace",
  "Escrow",
  "EscrowFactory",
  "AssetPassport",
  "AssetRegistry",
  "AssetOwnership",
  "AircraftRegistry",
  "ComponentRegistry",
  "DocumentRegistry",
  "MaintenanceRegistry",
  "FeeManager",
  "CredentialRegistry",
  "OrganizationRegistry",
  "ProtocolAddressRegistry",
  "RoleManager",
] as const;

/** Interfaces carrying the enum and error declarations the implementations use. */
export const INTERFACES = [
  "IMarketplace",
  "IEscrow",
  "IEscrowFactory",
  "IAssetRegistry",
  "IAssetOwnership",
  "IAircraftRegistry",
  "IComponentRegistry",
  "IDocumentRegistry",
  "IMaintenanceRegistry",
  "ICredentialRegistry",
  "IOrganizationRegistry",
  "IFeeManager",
  "IProtocolAddressRegistry",
  "IRoleManager",
] as const;

export type Artifact = {
  abi: readonly unknown[];
  ast?: { nodes?: AstNode[] };
};

export type AstNode = {
  nodeType?: string;
  name?: string;
  canonicalName?: string;
  members?: { name?: string }[];
  nodes?: AstNode[];
};

/** Reads a Foundry artifact, or returns null when the contract was not built. */
export async function readArtifact(name: string): Promise<Artifact | null> {
  try {
    const raw = await readFile(resolve(OUT_DIR, `${name}.sol`, `${name}.json`), "utf8");
    return JSON.parse(raw) as Artifact;
  } catch {
    return null;
  }
}

/** camelCase for file and export names: `AssetPassport` -> `assetPassport`. */
export function lowerFirst(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

export const BANNER = `// GENERATED by \`npm run codegen\` — do not edit by hand.
// Source: Foundry artifacts in ../out. Re-run after any contract change.
`;
